name: ACA INVENTORY JAVA API

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - src/Java.Store.InventoryApi/**
jobs:
  Build-Publish-ACA:
    uses: ./.github/workflows/Template_ACA.yml
    with:
      AZURE_CONTAINER_REGISTRY: acrcsughadoption
      CONTAINER_NAME: inventory-java-api
      DOCKER_PATH: ./src/Java.Store.InventoryApi/Dockerfile
      DOCKER_BUILD_CONTEXT: ./src/Java.Store.InventoryApi
      RESOURCE_GROUP: csughadoption-rg
    secrets: inherit